import { type NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="absolute block h-[46rem] w-full overflow-hidden z-0">
        <video
          autoPlay
          muted
          loop
          className="absolute top-0 left-0 h-[110%] w-fit blur -mt-12"
        >
          <source src="/loop.webm" type="video/webm" />
        </video>
        <div className="absolute top-1/2 h-1/2 w-full bg-gradient-to-b from-transparent to-black"></div>
      </div>
      <main className="min-h-screen w-full bg-black">
        <div className="w-full flex flex-col items-center container gap-12 px-4 py-16 m-0 mx-auto pt-72">
          <h1 className="text-5xl font-extrabold tracking-tight text-white backdrop-blur-lg sm:text-[5rem] p-5 px-6 z-10">
            Erwann
          </h1>
        </div>
      </main>
    </>
  );
};

export default Home;
